# Generated by Django 4.2.7 on 2023-11-25 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 11, 25, 17, 24, 53, 944028, tzinfo=datetime.timezone.utc), max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
