# Generated by Django 4.2.7 on 2023-12-16 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_category_auction_listing_auctioncategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='auctionWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WinningDate', models.DateTimeField(auto_now_add=True)),
                ('auctionName', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listing')),
                ('winnerNamee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('winningBid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid')),
            ],
        ),
    ]
