# Generated by Django 4.2.7 on 2023-12-16 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionwinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionwinner',
            name='auctionName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listing'),
        ),
        migrations.AlterField(
            model_name='auctionwinner',
            name='winningBid',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
    ]
