# Generated by Django 4.2.7 on 2023-12-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionwinner_auctionname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionwinner',
            old_name='winnerNamee',
            new_name='winnerName',
        ),
        migrations.RenameField(
            model_name='auctionwinner',
            old_name='auctionName',
            new_name='winningAuction',
        ),
    ]
