# Generated by Django 4.2.7 on 2023-12-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_winnernamee_auctionwinner_winnername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionwinner',
            old_name='winnerName',
            new_name='winner_Name',
        ),
        migrations.RenameField(
            model_name='auctionwinner',
            old_name='winningAuction',
            new_name='winning_Auction',
        ),
        migrations.RenameField(
            model_name='auctionwinner',
            old_name='winningBid',
            new_name='winning_Bid',
        ),
    ]
