# Generated by Django 4.2.7 on 2023-12-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_winnername_auctionwinner_winner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listing'),
        ),
    ]
