# Generated by Django 4.2.7 on 2023-12-18 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bid_bid_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionwinner',
            name='winning_Auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winAuction', to='auctions.auction_listing'),
        ),
    ]
