# Generated by Django 4.2.7 on 2023-12-18 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionwinner_winning_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionwinner',
            name='winning_Bid',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winningPrice', to='auctions.bid'),
        ),
    ]
