# Generated by Django 4.2.7 on 2023-12-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionwinner_winning_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionwinner',
            old_name='winning_Auction',
            new_name='winAuction',
        ),
        migrations.RenameField(
            model_name='auctionwinner',
            old_name='winning_Bid',
            new_name='winBid',
        ),
        migrations.RenameField(
            model_name='auctionwinner',
            old_name='winner_Name',
            new_name='winner',
        ),
        migrations.AlterField(
            model_name='auctionwinner',
            name='WinningDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
