# Generated by Django 4.2.7 on 2023-12-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_winning_auction_auctionwinner_winauction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionwinner',
            name='winAuction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='auctionwinner',
            name='winBid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
